import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const BASE = "/docs/reference/models";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "doc",
      id: "quickstart",
      label: "クイックスタート",
    },
    {
      type: "category",
      label: "API リファレンス",
      collapsible: true,
      collapsed: false,
      items: [
        { type: "doc", id: "api-reference/overview",         label: "概要" },
        { type: "doc", id: "api-reference/chat-completions", label: "テキスト生成" },
        { type: "doc", id: "api-reference/realtime",         label: "リアルタイム (WSS)" },
        { type: "doc", id: "api-reference/errors",           label: "エラーコード" },
      ],
    },
    {
      type: "category",
      label: "統合ガイド",
      collapsible: true,
      collapsed: true,
      items: [
        "guides/openai-sdk",
        "guides/anthropic-sdk",
        "guides/langchain",
        "guides/litellm",
        "guides/ollama-migration",
      ],
    },
    {
      type: "category",
      label: "ローカルLLM（オンプレミス）",
      collapsible: true,
      collapsed: true,
      items: ["guides/local-llm-install"],
    },
    {
      type: "category",
      label: "サンプル集（Cookbook）",
      collapsible: true,
      collapsed: false,
      link: { type: "doc", id: "cookbook/index" },
      items: [
        "cookbook/streaming",
        "cookbook/function-calling",
        "cookbook/structured-output",
        "cookbook/vision",
        "cookbook/embeddings",
        "cookbook/reasoning",
        "cookbook/error-handling",
        "cookbook/manga-manual",
      ],
    },
    {
      type: "category",
      label: "モデル一覧",
      collapsible: true,
      collapsed: false,
      link: { type: "doc", id: "reference/models" },
      items: [
        { type: "link", label: "DeepSeek", href: `${BASE}#deepseek` },
        {
          type: "category",
          label: "テキスト生成",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "概要", href: `${BASE}#alibaba-text` },
            { type: "link", label: "Qwen-Max（最上位テキスト）", href: `${BASE}#alibaba-text-1` },
            { type: "link", label: "Qwen-Plus（高コスパテキスト）", href: `${BASE}#alibaba-text-2` },
            { type: "link", label: "Qwen Flash（軽量テキスト）", href: `${BASE}#alibaba-text-3` },
            { type: "link", label: "Qwen-Turbo（高速テキスト）", href: `${BASE}#alibaba-text-4` },
            { type: "link", label: "QwQ（推論）", href: `${BASE}#alibaba-text-5` },
            { type: "link", label: "Qwen-Long（長文）", href: `${BASE}#alibaba-text-6` },
            { type: "link", label: "Qwen-Omni（マルチモーダル）", href: `${BASE}#alibaba-text-7` },
            { type: "link", label: "Qwen-Omni リアルタイム", href: `${BASE}#alibaba-text-8` },
            { type: "link", label: "QVQ（視覚推論）", href: `${BASE}#alibaba-text-9` },
            { type: "link", label: "Qwen-VL（視覚理解）", href: `${BASE}#alibaba-text-10` },
            { type: "link", label: "Qwen-OCR（文字認識）", href: `${BASE}#alibaba-text-11` },
            { type: "link", label: "Qwen-Math（数学）", href: `${BASE}#alibaba-text-12` },
            { type: "link", label: "Qwen-Coder（コード生成）", href: `${BASE}#alibaba-text-13` },
            { type: "link", label: "Qwen-MT（機械翻訳）", href: `${BASE}#alibaba-text-14` },
          ],
        },
        {
          type: "category",
          label: "テキスト生成（オープンソース）",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "概要", href: `${BASE}#alibaba-text-oss` },
            { type: "link", label: "Qwen3.6（オープンソース）", href: `${BASE}#alibaba-text-oss-1` },
            { type: "link", label: "Qwen3.5（オープンソース）", href: `${BASE}#alibaba-text-oss-2` },
            { type: "link", label: "Qwen3（オープンソース）", href: `${BASE}#alibaba-text-oss-3` },
            { type: "link", label: "Qwen-Omni（マルチモーダル）", href: `${BASE}#alibaba-text-oss-4` },
            { type: "link", label: "Qwen3-Omni Captioner（音声キャプション）", href: `${BASE}#alibaba-text-oss-5` },
            { type: "link", label: "Qwen-VL（視覚理解）", href: `${BASE}#alibaba-text-oss-6` },
            { type: "link", label: "Qwen-Coder（コード生成）", href: `${BASE}#alibaba-text-oss-7` },
          ],
        },
        {
          type: "category",
          label: "画像・動画生成",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "概要", href: `${BASE}#alibaba-image` },
            { type: "link", label: "Qwen テキスト→画像生成", href: `${BASE}#alibaba-image-1` },
            { type: "link", label: "Qwen 画像編集", href: `${BASE}#alibaba-image-2` },
            { type: "link", label: "Qwen Z-Image（テキスト→画像）", href: `${BASE}#alibaba-image-3` },
            { type: "link", label: "Wan テキスト→画像生成", href: `${BASE}#alibaba-image-4` },
            { type: "link", label: "Wan 画像生成・編集", href: `${BASE}#alibaba-image-5` },
            { type: "link", label: "Wan 汎用画像編集", href: `${BASE}#alibaba-image-6` },
            { type: "link", label: "動画生成", href: `${BASE}#alibaba-image-7` },
            { type: "link", label: "HappyHorse 画像→動画（先頭フレーム）", href: `${BASE}#alibaba-image-8` },
            { type: "link", label: "HappyHorse 参照→動画", href: `${BASE}#alibaba-image-9` },
            { type: "link", label: "HappyHorse 動画編集", href: `${BASE}#alibaba-image-10` },
            { type: "link", label: "Wan テキスト→動画", href: `${BASE}#alibaba-image-11` },
            { type: "link", label: "Wan 画像→動画", href: `${BASE}#alibaba-image-12` },
            { type: "link", label: "Wan 画像→動画（先頭フレーム）", href: `${BASE}#alibaba-image-13` },
            { type: "link", label: "Wan 画像→動画（先頭・末尾フレーム）", href: `${BASE}#alibaba-image-14` },
            { type: "link", label: "Wan 参照→動画", href: `${BASE}#alibaba-image-15` },
            { type: "link", label: "Wan 動画編集", href: `${BASE}#alibaba-image-16` },
            { type: "link", label: "Wan 画像→アクション動画", href: `${BASE}#alibaba-image-17` },
            { type: "link", label: "Wan 動画人物差し替え", href: `${BASE}#alibaba-image-18` },
          ],
        },
        {
          type: "category",
          label: "音声合成（テキスト読み上げ）",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "概要", href: `${BASE}#alibaba-tts` },
            { type: "link", label: "Qwen-TTS（音声合成）", href: `${BASE}#alibaba-tts-1` },
            { type: "link", label: "Qwen-TTS リアルタイム", href: `${BASE}#alibaba-tts-2` },
            { type: "link", label: "Qwen-TTS 音声クローン", href: `${BASE}#alibaba-tts-3` },
            { type: "link", label: "Qwen-TTS 音声デザイン", href: `${BASE}#alibaba-tts-4` },
            { type: "link", label: "CosyVoice（音声合成）", href: `${BASE}#alibaba-tts-5` },
          ],
        },
        {
          type: "category",
          label: "音声認識（文字起こし・翻訳）",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "概要", href: `${BASE}#alibaba-asr` },
            { type: "link", label: "Qwen LiveTranslate（リアルタイム翻訳）", href: `${BASE}#alibaba-asr-1` },
            { type: "link", label: "Qwen ASR（音声認識）", href: `${BASE}#alibaba-asr-2` },
            { type: "link", label: "Qwen ASR リアルタイム", href: `${BASE}#alibaba-asr-3` },
            { type: "link", label: "Fun-ASR（音声認識）", href: `${BASE}#alibaba-asr-4` },
            { type: "link", label: "リアルタイム音声認識", href: `${BASE}#alibaba-asr-5` },
          ],
        },
        {
          type: "category",
          label: "ベクトル（埋め込み）",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "概要", href: `${BASE}#alibaba-embed` },
            { type: "link", label: "テキストベクトル", href: `${BASE}#alibaba-embed-1` },
            { type: "link", label: "マルチモーダルベクトル", href: `${BASE}#alibaba-embed-2` },
          ],
        },
        {
          type: "category",
          label: "リランキング（並べ替え）",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "概要", href: `${BASE}#alibaba-rerank` },
            { type: "link", label: "テキストリランキング", href: `${BASE}#alibaba-rerank-1` },
          ],
        },
        {
          type: "category",
          label: "業界モデル",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "link", label: "概要", href: `${BASE}#alibaba-industry` },
            { type: "link", label: "意図理解", href: `${BASE}#alibaba-industry-1` },
            { type: "link", label: "ロールプレイ", href: `${BASE}#alibaba-industry-2` },
          ],
        },
      ],
    },
    {
      type: "doc",
      id: "guides/auto-model-selection",
      label: "自動モデル選択（lykuro/auto）",
    },
    {
      type: "category",
      label: "リファレンス",
      collapsible: true,
      collapsed: true,
      items: [
        "reference/pricing",
        "reference/rate-limits",
        "reference/error-codes",
        "reference/deprecations",
      ],
    },
    {
      type: "doc",
      id: "faq",
      label: "FAQ",
    },
  ],

  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api-reference",
    },
  ],
};

export default sidebars;
